services:
  - type: web
    name: bunk-predictor-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT bunk_api:app"
    rootDir: backend
    pythonVersion: 3.11.9
